# Generated by Django 5.1.3 on 2024-11-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhanish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Phone', models.IntegerField(max_length=10)),
                ('Email', models.EmailField(max_length=255)),
                ('Password', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=300)),
                ('Profile', models.ImageField(upload_to='profile')),
            ],
        ),
    ]
