# Generated by Django 5.1.3 on 2024-11-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhanish', '0002_alter_orderitem_price_at_time_of_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default=11, max_length=2),
            preserve_default=False,
        ),
    ]
